Major enhancements to the build tools (Updated)
longsleep/build-pine64-image pull request #53
Opened 2017-03-28 08:34 UTC by Terra854

#52

2017-04-01 16:17 UTC, longsleep commented
Would you please split this up in multiple pull requests. I can take some of the changes, but do not like others. It would be better to have those discussed individually.

2017-04-01 16:36 UTC, longsleep requested changes
I know i request lots of changes. Please understand that i use similar tools for various target platforms and i constantly reuse code between them. My intention is to keep them as simple as possible not as user friendly as possible.

2017-04-01 16:36 UTC, longsleep commented on build-pine64-image.sh
> +if [ ! -d "$PWD/$OUTPUT" ]; then
Please do not change usage or behavior in a way which is incompatible with how the scripts currently work.

2017-04-01 16:36 UTC, longsleep commented on build-pine64-image.sh
> +	echo "ERROR: You need to install zerofree in order to generate a pine64 image."
Please do not introduce additional dependencies. If you insist on having this, make it optional and create a seperate pull request.

2017-04-01 16:36 UTC, longsleep commented on build-pine64-image.sh
> +echo ""
Please remove all these changes. This is not a end user tool and i would very much prefer the script to be as minimal as possible.

2017-04-01 16:36 UTC, longsleep commented on simpleimage/make_rootfs.sh
> +	done
These changes potentiall never return. If for whatever reason umount fails the script should just continue and not wait forever.

2017-04-01 16:36 UTC, longsleep commented on simpleimage/make_rootfs.sh
> +	arch|arch-lcd)
Bad idea to use the $DISTRO variable for lcd variant. Please find another way so $DISTRO is always the distro and not something else.

2017-04-01 16:36 UTC, longsleep commented on simpleimage/make_rootfs.sh
> +mount --bind /dev/pts $DEST/dev/pts
Why is this required?

2017-04-01 16:36 UTC, longsleep commented on simpleimage/make_rootfs.sh
> +echo "# For the prompt below, please answer it with 'a' for optimum performance #"
Why would it ever prompt? Please do not introduce changes which require interaction.

2017-04-01 16:36 UTC, longsleep commented on simpleimage/make_simpleimage.sh
> +	echo "Usage: $0 <image-type> <image-file.img> <kernel-tarball-or-folder> [disk size in MiB]"
Do not change the usage (keep parameter order as is).

2017-04-04 07:30 UTC, Terra854 commented on simpleimage/make_rootfs.sh
> +mount --bind /dev/pts $DEST/dev/pts
Without /dev mounted, the script throws errors on my end saying that needed files in /dev are missing (because it is not mounted).

2017-04-13 20:33 UTC, longsleep commented
Continues in #55

2017-04-13 20:33 UTC, closed without merging