Major enhancements to the build tools (V2)
longsleep/build-pine64-image pull request #55
Opened 2017-04-04 08:19 UTC by Terra854

Updated from #53

2017-04-04 17:54 UTC, longsleep requested changes

2017-04-04 17:54 UTC, longsleep commented on simpleimage/make_rootfs.sh
> +			if [ ! "$LCD" = "-lcd" ]
Please change this comparison to check for a "1" variable which is set on the top of the script based on commandline parameter. Rest looks good. Also, please do not open new pull requests all the time. Use the existing one thanks!

2017-04-07 15:22 UTC, Terra854 commented on simpleimage/make_rootfs.sh
> +			if [ ! "$LCD" = "-lcd" ]
New branch, therefore need new PR

2017-04-13 20:33 UTC, longsleep requested changes
Please push the next changes to the same branch. You do not need to create another pull request if you do this.

2017-04-13 20:33 UTC, longsleep commented on simpleimage/make_simpleimage.sh
> +	echo "Usage: $0 <image-type> <image-file.img> [disk size in MiB] [kernel-tarball]"
This still changes usage, please avoid that. Add another parameter at the end instead.

2017-04-13 20:33 UTC, longsleep commented on simpleimage/make_rootfs.sh
> +				DISPTOOLCMD="apt-get -y install sunxi-disp-tool"
Why does this matter / is it not installed when using LCD?

2017-04-13 20:33 UTC, longsleep commented on simpleimage/make_rootfs.sh
> +	echo "LCD=1       Enable LCD support"
I do not see how this actually works. How is this variable set when passed as last argument to the script?

2017-04-13 20:33 UTC, longsleep commented on simpleimage/make_rootfs.sh
> +	set +e
Instead of this, please use !! true for commands which are allowed to fail.

2017-04-13 20:33 UTC, longsleep commented on simpleimage/make_rootfs.sh
> +				DISPTOOLCMD="apt-get -y install sunxi-disp-tool"
Why is the disp-tool not installed in LCD case? The tool should work there too.

2017-04-13 20:33 UTC, longsleep commented on simpleimage/make_rootfs.sh
> +nameserver 8.8.8.8
Why hardcode googles nameservers?

2017-04-13 20:33 UTC, longsleep commented on simpleimage/make_rootfs.sh
> +		wget http://files.pine64.org/opensuse/tools/pine64-config/opensuse/pine64-config.sh -O $DEST/usr/local/sbin/pine64-config.sh
This adds a third party script? Can this be avoided? If you want this script as part of images which are built from my gear please submit a seperate pull request to add it.

2017-04-13 20:33 UTC, longsleep commented on simpleimage/make_simpleimage.sh
> +	echo "Usage: $0 <image-type> <image-file.img> [disk size in MiB] [kernel-tarball]"
Please do not change the usage of existing scripts. I want to keep it backwards compatible, so add new parametes to the end.

2017-04-15 12:32 UTC, Terra854 commented on simpleimage/make_rootfs.sh
> +	echo "LCD=1       Enable LCD support"
Well, it works on my end, so it shouldn't be a problem

2017-04-15 12:33 UTC, Terra854 commented on simpleimage/make_rootfs.sh
> +				DISPTOOLCMD="apt-get -y install sunxi-disp-tool"
The tool should not be installed or the LCD will not work properly

2017-04-15 12:34 UTC, Terra854 commented on simpleimage/make_rootfs.sh
> +				DISPTOOLCMD="apt-get -y install sunxi-disp-tool"
LCD does not work properly if the tool is installed

2017-04-15 12:37 UTC, Terra854 commented on simpleimage/make_rootfs.sh
> +nameserver 8.8.8.8
opensuse afaik does not auto-generate resolv.conf or have the resolvconf tool available

2017-04-15 12:39 UTC, Terra854 commented on simpleimage/make_rootfs.sh
> +		wget http://files.pine64.org/opensuse/tools/pine64-config/opensuse/pine64-config.sh -O $DEST/usr/local/sbin/pine64-config.sh
It adds my pine64-config tool to the opensuse images, which is needed as it contains modifications to the platform-scripts for it to work on opensuse

2017-04-25 19:01 UTC, longsleep commented on simpleimage/make_rootfs.sh
> +		wget http://files.pine64.org/opensuse/tools/pine64-config/opensuse/pine64-config.sh -O $DEST/usr/local/sbin/pine64-config.sh
What changes to the platform-scripts? Can you add seperate pull requests for those. I want to avoid a extra custom repository.

2017-04-25 19:02 UTC, longsleep commented on simpleimage/make_rootfs.sh
> +nameserver 8.8.8.8
Mhm this sounds strange and wrong. If DNS resolution is required during install, then copy the hosts resolv.conf as done with the other distros and clean it up when its no longer required and let the distribution do whatever DNS resolution it needs.

2017-04-25 19:03 UTC, longsleep commented on simpleimage/make_rootfs.sh
> +				DISPTOOLCMD="apt-get -y install sunxi-disp-tool"
Then the tool should be fixed or not run in case of LCD. Do you have details?

2017-04-25 19:12 UTC, longsleep requested changes
Please also change the pine64lcd.dts to use the same format than the existing pine64.dts, so changes can be made easily.

2017-04-25 19:12 UTC, longsleep commented on simpleimage/make_rootfs.sh
> +UNTAR="tar xzpsf"
This is not the same. It is intentionally using bsdtar here - please keep it.

2017-04-26 14:13 UTC, Terra854 commented
What format are you talking about?

2017-04-30 14:47 UTC, longsleep commented
Can you please remove the lcd stuff for now - i decided not to merge this until i have time for some thought on it as the Pinebook changes are already complicated enough.

I am willing to merge the OpenSUSE part without dependency to external repositories and without hardcoded nameservers.

2017-04-30 14:51 UTC, longsleep commented on simpleimage/make_rootfs.sh
> +mount --bind /dev/pts $DEST/dev/pts
These mounts make no sense - they are only needed in the chroot (if at all) and thus should be added to the do_chroot function.

2017-10-13 16:14 UTC, longsleep commented
Closing, please split up and open a new pr when still interested. Thank you!

2017-10-13 16:14 UTC, closed without merging